# LDA

In [15]:
class LDA:
    from random import randint
    import pandas as pd
    def __init__(self,doc_ls,topic_num,alpha=0.1,beta=0.001):
        self.alpha = alpha
        self.beta = beta
        self.k = topic_num
        self.start_df = self.RandomlyAssignTopic(doc_ls)
    
    
    def RandomlyAssignTopic(self,doc_ls):
        from random import randint
        import pandas as pd
        token = []
        for i in range(len(doc_ls)):
            for j in doc_ls[i].split(' '):
                token_dict = {}
                token_dict['token'] = j
                token_dict['doc'] = i
                token_dict['topic'] = randint(1,self.k)
                token.append(token_dict)
        token_df = pd.DataFrame(token)
        return token_df
        pass
    
    def IterateAssignTopic(self):
        start_df = self.start_df
        for i in range(len(start_df)):
            for j in range(len(self.topic_num)):
                if j in start_df.loc[start_df['doc']==i].value_counts().index:
                    start_df.loc[start_df['doc']==i][j]=start_df.loc[start_df['doc']==i].value_counts()[j]
        return start_df
        pass
    
    #토픽별 주요 키워드 출력
    def TopicModeling(self):
        pass

In [16]:
lda = LDA(doc_ls,3)

In [17]:
doc_ls = ['Cute kitty','Eat rice or cake','Kitty and hamster','Eat bread','Rice bread and cake','Cute hamster eats bread and cake']

In [18]:
len(doc_ls)

6

In [19]:
lda.start_df

    doc    token  topic
0     0     Cute      2
1     0    kitty      3
2     1      Eat      2
3     1     rice      1
4     1       or      2
5     1     cake      3
6     2    Kitty      1
7     2      and      3
8     2  hamster      1
9     3      Eat      1
10    3    bread      1
11    4     Rice      3
12    4    bread      1
13    4      and      3
14    4     cake      3
15    5     Cute      2
16    5  hamster      3
17    5     eats      2
18    5    bread      3
19    5      and      2
20    5     cake      3